# Generated by Django 4.0.2 on 2022-02-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('discount', models.IntegerField(max_length=100, null=True)),
                ('base_price', models.IntegerField()),
                ('final_price', models.IntegerField()),
                ('manufacturing_country', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
