# Generated by Django 4.0.2 on 2022-02-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_item_base_price_alter_item_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='base_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='final_price',
            field=models.IntegerField(),
        ),
    ]
