# Generated by Django 4.0.2 on 2022-02-14 17:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_item_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_description', models.TextField(null=True)),
                ('last_date', models.DateField(default=datetime.datetime.now)),
                ('last_registration_date', models.DateField(default=datetime.datetime.now)),
                ('change_date', models.DateField(default=datetime.datetime.now)),
                ('base_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.invoice')),
                ('last_items', models.ManyToManyField(to='core.Item')),
                ('last_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.invoicetype')),
                ('last_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.invoicetype'),
        ),
        migrations.AlterField(
            model_name='item',
            name='manufacturing_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.country'),
        ),
    ]
